/**
 * determinator-ls-example.ts
 *
 * Przykładowy skrypt dla agenta determinator.
 * Wykonuje "ls -la" w cwd, zapisuje wynik do output.
 *
 * Użycie:
 *   /run determinator '{"script": "'$(pwd)'/examples/determinator-ls-example.ts"}'
 */

import * as path from "node:path";
import type { DeterminatorScript } from "../src/determinator/interface";

const script: DeterminatorScript = async (ctx) => {
  ctx.log("Starting determinator-ls-example...");

  const { stepContext } = ctx;
  const chainDir = stepContext.chain_dir;
  const outputPath = stepContext.output ?? path.join(chainDir, "determinator-output.md");
  const resolvedInputs = stepContext.reads.map((r) =>
    path.isAbsolute(r) ? r : path.join(chainDir, r),
  );

  // Wykonaj ls -la
  const { stdout, stderr } = await ctx.exec("ls -la");

  const readmeContent = resolvedInputs.length > 0
    ? await ctx.readFile(resolvedInputs[0]!).catch(() => "(file not found)")
    : "(no inputs)";

  // Zbuduj raport
  const content = [
    "# Deterministic LS Report\n",
    `Generated by determinator at ${new Date().toISOString()}\n`,
    "## Directory listing\n",
    "```",
    stdout,
    "```\n",
    "## Errors",
    stderr ? `\`\`\`\n${stderr}\n\`\`\`` : "(none)\n",
    "## Context\n",
    `- **cwd**: ${ctx.cwd}`,
    `- **reads**: ${stepContext.reads.join(", ") || "(none)"}`,
    `- **output**: ${outputPath}`,
    `- **chainDir**: ${chainDir}`,
    `- **runId**: ${stepContext.run_id}`,
    `- **params**: ${JSON.stringify(ctx.params)}`,
    "",
    "## Step context (raw)\n",
    "```json",
    JSON.stringify(stepContext, null, 2),
    "```\n",
    "## First input preview",
    "```",
    readmeContent.slice(0, 500),
    "```",
  ].join("\n");

  await ctx.writeFile(outputPath, content);
  ctx.log("Report written successfully");

  return { exitCode: 0, output: content };
};

export default script;
